Make login cookies check more robust.
TheM4hd1/SwiftyInsta pull request #249
Opened 2021-05-14 12:39 UTC by pxrne

The aim of this PR is to make the checking for cookies more robust when logging in.

Cookies are not always set at page load so the current method could fail and an infinite spinner would be presented to the user, the callback never being called.

The solution is to check for cookies perpetually. When the cookies are eventually set, the callback is called and the end result is the same as before.

2021-05-15 18:44 UTC, sbertix commented
Hey @pxrne, 

I've just seen this as both me and @TheM4hd1 are no longer actively maintaining this repo (please check out #244). 
I agree that the cookie check in **SwiftyInsta** `LoginWebView` is sub-par (I'm the one who wrote it so I'm not offending one hahaha), and the fact that I moved past it in [**Swiftagram**](https://github.com/sbertix/Swiftagram) speaks volumes. 

However, the issue here is about concurrency, being the check asynchronous, not the actual time cookies are cached. 
Although a solution, I'm not really sure this is the best one. It creates unnecessary checks (especially for Facebook login or when dealing with 2FA) and leaves the user wondering for _up to_ a second (admittedly only in the worst case scenario, which is however not that unlikely) whether the authentication succeeded or not. 

I'm not really sure this is better than using a semaphore ([here's just a reference on a possible implementation](https://github.com/sbertix/Swiftagram/blob/main/Sources/Swiftagram/Authentication/Visual/AuthenticatorWebView.swift)). 
What do you think? 

Again though, this is still a fix, so I'm inclined to merge this after hearing back from you.

2021-05-16 10:42 UTC, pxrne commented
Indeed it does create unnecessary checks while the user is proceeding with the login, however this makes it more robust imo, I've learned the hard way to make things redundant and robust working with these private apis 😅. The leaving user wondering I don't think is an issue as a loader is presented to them at the time. 

Looked at your code. It seems like you are still doing the check only on page loads? Forgive me if I am wrong I only worked with semaphores once before haha.
Also you are checking absolute string of the url, what if instagram decide to add a query param or something similar (?hl=en comes to mind), you would never error out?

2021-05-16 13:19 UTC, pxrne commented
Sorry I'm still having trouble understanding how you solve for the fact that the cookieStore doesn't have the session cookies set up to a couple seconds after the page load? the getAllCookies isn't a callback or delegate method that only happens on cookies being set.

2021-05-16 13:34 UTC, sbertix commented
> Sorry I'm still having trouble understanding how you solve for the fact that the cookieStore doesn't have the session cookies set up to a couple seconds after the page load? the getAllCookies isn't a callback or delegate method that only happens on cookies being set.

I'm saying that there's a difference between what you're claiming to be happening, and appears to be happening (i.e. "cookies are not set when navigation is finished"), and what actually happens (i.e. "race conditions in `getAllCookies(_:)` mean that `webView(_:didFinish:)` finishes and gets called again before `getAllCookies(_:)` actually completes, so cookies are not updated until after `getAllCookies(_:)` does eventually return"). It's easier to understand what I mean by putting a breakpoint inside the actual completion handler: it does not solve the problem for good. Move the breakpoint outside of it, and suddenly it does. 

This commit fixes the symptoms (again, "cookies appear to be empty immediately after loading the page") and not the actual cause (again, "race condition […]"). It has nothing to do with delegates, callbacks, or `WKHTTPCookieStore` per se. 

> Is this good enough? 

Again, it probably is. 

> Is this botched?

Very match so: timers are unreliable, they get paused on user interaction and it's overall less efficient.

> Is this a problem? 

Not really: it's better than authentication failing silently. But we must be on the same page about it not being a "cure", just a "band-aid". 

I hope what's actually going on in `LoginWebView` is a bit more clear, now. 
That said, I'm gonna test it some more in a couple hours and consider merging this.

2021-05-16 15:55 UTC, sbertix commented
Hey @pxrne, 
Do you mind also updating `s.version` in `SwiftyInsta.podspec` to `2.5.0`? I'll go ahead and merge it afterwards 💪

2021-05-16 16:00 UTC, sbertix requested changes
Hey @pxrne,
Do you mind also updating `s.version` in `SwiftyInsta.podspec` to `2.5.0`? I'll go ahead and merge it afterwards 💪

2021-05-16 18:31 UTC, pxrne commented
All right bumped pod vesion. Xcode marketing version is still at 2.1.3 though. Also not sure how to update spm version.

2021-05-16 18:57 UTC, sbertix commented
> All right bumped pod vesion. Xcode marketing version is still at 2.1.3 though. Also not sure how to update spm version.
> 
> https://github.com/TheM4hd1/SwiftyInsta/blob/756bf2e0635246be401aa2cc1341af6734bb3858/SwiftyInsta.xcodeproj/project.pbxproj#L1258

It doesn't really matter tbh. All it needs is the updated version in the `.podspec` for **CocoaPods**  and the tag I'll create after merging this for **SPM**. 
Thank again for this fix 💪

2021-05-16 18:57 UTC, merged